version: '3.5'

services:
  postgres:
    image: postgres:9.6-alpine
    container_name: "postgres"
    env_file:
      - local.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  mmock:
    image: jordimartin/mmock:v3.0.3
    container_name: "mmock"
    ports:
      - 8082:8082
      - 8083:8083
    volumes:
       - ./mmock-config:/config
