version: '3.5'

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    restart: always
    environment:
      - MONGO_DATA_DIR=./.data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="user"
      - MONGODB_PASS="1234"
    volumes:
      - ./.data/db:/data/db
    ports:
      - 27017:27017
